name: lint
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths:
      - '**.go'
      - 'revive.toml'
      - '.github/workflows/lint.yaml'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Install revive
      run: go install github.com/mgechev/revive@v1.3.7

    - name: Check formatting
      run: revive -config revive.toml -formatter friendly ./...
