name: test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths:
      - '**.go'
      - '.github/workflows/test.yaml'

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Install ginkgo
      run: go install github.com/onsi/ginkgo/v2/ginkgo

    - name: Do tests
      run: ginkgo -r --fail-on-pending --cover --trace --race
